/**
 * What each of the nine declarations says, carried over from the firm's own documents. The employee reads
 * this and then answers what the declaration asks; the words here are never rewritten.
 *
 * Generated from the documents in the API's declarations resources.
 */

export interface WordingBlock {
  kind: string;
  text: string;
  strong: boolean;
  /** The mark the paper puts against it, where it numbers or letters one. */
  number: string | null;
  /** A table's cells, row by row, where the block is one. */
  rows: string[][];
}

export interface DeclarationWording {
  /** What the paper prints in each gap it leaves, such as the firm's own name. */
  printed: Record<string, string>;
  blocks: WordingBlock[];
}

export const declarationWording: Record<string, DeclarationWording> = {
  CONFLICT_OF_INTEREST: {
    printed: {"firmName": "AMALTAS PARTNERS LIMITED"},
    blocks: [
      { kind: "PARAGRAPH", text: "{{firmName}}", strong: false, number: null, rows: [] },
      { kind: "HEADING", text: "Conflict of Interest Declaration and Management Form", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Employee name:"], ["Position Title:"], ["Important information:"], ["Instructions for completing this form"], ["1. Who must complete this form\na. Any employee who has identified a conflict between their private interests and public duties.\nb. Any workplace participant (e.g. employees, contractors/consultants) assessed as warranting a declaration on the basis of potential, perceived or actual conflict of interest risk ]\n2. How often must this form be completed\na. This form must be completed:\nAt the time of joining\nAt the time a conflict of interest is identified.\nAnnually\n3. What to do with the completed form\na. The following steps must be taken to complete the declaration process:\nEmployee to complete Sections A and B of the form and provide to manager;\nManager, Compliance and employee to complete risk management plan at Section C (where relevant) and sign declaration at Section D; and\nDefinition to assist in completing this form:\nConflict of interest: a conflict of interest arises when an employee has private interest that could improperly influence, or be seen to influence, their decisions or the performance of their duties. Conflicts can be actual, potential or perceived and can be financial or non-financial in nature."]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section A. Identification of a conflict of interest risk"], ["A.1 I have made the following assessment:\n(tick appropriate box)", "No risk of conflict of interest identified\n☐ I have considered the nature of the duties, considered my professional duties and personal interests and declare that to the best of my knowledge no actual, potential or perceived conflict risk of exists. [Go to section C]\nRisk of conflict of interest identified\n☐ I have considered the nature of the duties, considered my professional duties and personal interests and consider that an actual, potential or perceived conflict of interest risk exists. [Go to section B]"]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section B. Conflict of interest management plan"], ["B1. Type of conflict of interest identified"], ["The following conflict of interest risk was identified:\nUseful information: state the specific personal interest identified (e.g. relationship with employee/friend/family; financial interest; conflict of duty etc.) and detail how this raises an actual potential or perceived conflict of interest with the employee’s public duties"], [""], ["B2. Management plan for employee’s conflict of interest"], ["The employee and manager will take the following action to manage the conflict of interest:\nUseful information: this management plan will ensure conflict risks are managed and resolved in favour of the firm’s and client’s interest rather than that of the employee and will be based on the following mitigation strategies:\nRestrict: restrictions are placed on the employee’s involvement in the matter\nRecruit: a disinterested third party is used to oversee part or all of the process that deals with the matter\nRemove: the employee removes themselves, or is removed, from the matter\nRelinquish or Resign: the employee relinquishes the private interest that is creating the conflict. Where relinquishing the interest is not possible (e.g. relationship with family) and the conflict cannot be managed in the public interest using one of the other options above, the employee may consider resigning."], [""], ["B3. The employee and manager will ensure this management plan is reviewed:", "☐ Within 1 month ☐ Within 3 months ☐ Within 6 months\n☐ Within 12 months ☐ N/A as the conflict is a one-off of short duration\n☐ Other (specify):"]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section C. Declarations"], ["C.1 Employee declaration"], ["In order to treat Clients fairly, I acknowledge that the Firm must take reasonable steps to ensure that conflicts and potential conflicts of interest between itself and its Clients and between one Client and another are identified and then prevented or managed in such a way that the interests of a Client are not adversely affected and to ensure that all of its Clients are fairly treated and not prejudiced by any such conflicts of interest.\nI understand that when assessing the appropriateness of any advice or product I provide to a Client, only that Client’s interests should be considered and that any other Client’s interests, the Firm’s interests or other individual’s interests should be disregarded.\nI further understand that where any business or personal relationship or interest gives rise to a potential conflict of interest that would be too material to be disregarded in that the Firm would be unable to prevent or manage such a COI, I must decline to act for that Client and inform Compliance immediately.\nI declare that to best of my knowledge, the information in this form is true and correct. Any actions described in Section B of the form have been put in place to effectively manage any actual, perceived or potential conflict of interest. I undertake to adhere to any conflict of interest risk management plan set out in Section B to ensure that the firm’s reputation and the public interest is adequately protected.\nI undertake to make further declaration should a change in my circumstances give rise to an expectation of a conflict of interest."], ["Signature of Employee: _________________________\nName (please print): _________________________\nDate: ______/______/______"], ["C.2 Manager declaration"], ["I undertake to adhere to any conflict of interest risk management plan set out in Section C, and to monitor my employee’s adherence to the management plan, which is in place to ensure that the Department’s reputation and the public interest is adequately protected."], ["Signature of Manager: _________________________\nName (please print): _________________________\nDate: ______/______/______"], ["Compliance Officer:\nSign:\nDate____"]] },
    ],
  },
  AML_PROCEDURES_CERTIFICATION: {
    printed: {"firmName": "AMALTAS PARTNERS LIMITED"},
    blocks: [
      { kind: "PARAGRAPH", text: "{{firmName}}", strong: false, number: null, rows: [] },
      { kind: "HEADING", text: "AML Procedures Certification", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "To:", strong: true, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "The MLRO", strong: true, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I hereby acknowledge receipt of the AML Manual. I am either aware of the location of the AML Manual should I need to access it or agree I will keep the AML Manual for further reference. I represent that I have read and understood all the provisions in the AML Manual and agree to abide by and accept the policies and procedures contained herein.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand, acknowledge and agree that all the provisions of the Firm’s AML Manual apply to me.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "By signing this certification, I hereby acknowledge that", strong: false, number: null, rows: [] },
      { kind: "CHECKBOX", text: "I am a new joinee and accept that the requirements set out in the manual form part of my employment contract", strong: false, number: null, rows: [] },
      { kind: "CHECKBOX", text: "Annual Certification - I have at all times, and will continue to be, in compliance with both the spirit and the specific requirements of all of the provisions of the Firm’s Compliance Manual.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand that failure to comply with the requirements of the Manual and/or any DFSA Principles, rules and/or regulations may have serious consequences for the Firm and its Employees.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I will observe and comply with all of the Firm’s requirements on AML /CDD that may be amended from time to time; and", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I have, and will continue to act and conduct in line with this manual, DFSA principles, rules and regulations. When in doubt, I will discuss with MLRO as to the specific rules.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand that any breaches may result disciplinary actions including termination of employment.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Name:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Signature:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Date:", strong: false, number: null, rows: [] },
    ],
  },
  AUTHORISED_INDIVIDUALS: {
    printed: {"firmName": "AMALTAS PARTNERS LIMITED"},
    blocks: [
      { kind: "PARAGRAPH", text: "{{firmName}}", strong: false, number: null, rows: [] },
      { kind: "HEADING", text: "Authorised Individuals Declaration", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I hereby undertake that I will comply with the rules and regulations stipulated by DFSA at all times.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I will follow the principles for authorised individuals stated in the DFSA rule book.", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Principle", "Summary"], ["Integrity", "Will observe high standards of integrity and fair dealing in carrying out every Licensed Function"], ["Due skill, care and diligence", "Will act with due skill, care and diligence in carrying out every Licensed Function"], ["Market conduct", "Will observe proper standards of conduct in financial markets in carrying out every Licensed Function."], ["Relations with the DFSA", "Will deal with the DFSA in an open and cooperative manner and will disclose appropriately any information of which the DFSA would reasonably be expected to be notified."], ["Management, systems and control", "Will take reasonable care to ensure that the business is organised so that it can be managed and controlled effectively."], ["Compliance", "Will take reasonable care to ensure that the firm complies with any legislation applicable in the DIFC."]] },
      { kind: "PARAGRAPH", text: "I acknowledge that breaching a Principle stated for Authorised Individuals makes me liable to disciplinary action and may indicate that I am no longer fit and proper to perform a Licensed Function and the DFSA may consider suspending or withdrawing Authorised Individual status on that basis.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Name:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Signature:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Date:", strong: false, number: null, rows: [] },
    ],
  },
  COMPLIANCE_MANUAL_CERTIFICATION: {
    printed: {"firmName": "AMALTAS PARTNERS LIMITED"},
    blocks: [
      { kind: "PARAGRAPH", text: "{{firmName}}", strong: false, number: null, rows: [] },
      { kind: "HEADING", text: "Compliance Manual Certification (Annual / new Joinee)", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "To: Compliance Officer", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I hereby acknowledge receipt of the Compliance Manual. I am either aware of the location of the Compliance Manual should I need to access it or agree I will keep the Compliance Manual for further reference. I represent that I have read and understood all the provisions in the Compliance Manual and agree to abide by and accept the policies and procedures contained herein.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand, acknowledge and agree that all the provisions of the Firm’s Compliance Manual apply to me.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "By signing this certification, I hereby acknowledge that", strong: false, number: null, rows: [] },
      { kind: "CHECKBOX", text: "I am a new joinee and accept that the requirements set out in the manual form part of my employment contract", strong: false, number: null, rows: [] },
      { kind: "CHECKBOX", text: "I have at all times, and will continue to be, in compliance with both the spirit and the specific requirements of all of the provisions of the Firm’s Compliance Manual.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand that failure to comply with the requirements of the Manual and/or any DFSA Principles, rules and/or regulations may have serious consequences for the The Firm and its Employees.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I have, and will continue to act and conduct in line with this manual, DFSA principles, rules and regulations. When in doubt, I will discuss with Compliance as to the specific rules.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand that any breaches may result disciplinary actions including termination of employment.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Name:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Signature:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Date:", strong: false, number: null, rows: [] },
    ],
  },
  OUTSIDE_INTERESTS: {
    printed: {"firmName": "AMALTAS PARTNERS LIMITED"},
    blocks: [
      { kind: "PARAGRAPH", text: "{{firmName}}", strong: false, number: null, rows: [] },
      { kind: "HEADING", text: "Declaration and Management of Outside Interests Form", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Employee name:"], ["Important information:"], ["Instructions for completing this form"], ["1. Who must complete this form\na. All Executive Officers.\nb. All Employees\nc. Any workplace participant (e.g. employees, contractors/consultants) assessed as warranting a declaration on the basis of potential, perceived or actual conflict of interest risk\n2. How often must this form be completed\nThis form must be completed:\nupon appointment to a position listed at point 1 above; and\nannually after appointment; and\nwithin five working days after the employee’s circumstances change.\n3. Filling in this form\na. Complete the form as accurately and comprehensively as possible.\nb. Section A is to be completed in all cases. Sections B to D to be completed only in situations of potential conflict\nc. Type or write your answers legibly.\nd. Provide an answer for each question. Do not leave any questions unanswered.\ne. See Conflict of interest policy for further information and contact details for advice on completing this form."]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section A. Outside Business interests"], ["Definitions to assist in completing this section:\nFamily (Qns A4 to A6): this includes your immediate family (e.g. husband, wife, spouse, partner, child, parent or sibling) or those family members who are wholly or substantially dependent on you and whose affairs are closely linked. Family interests refers only to interests that are known to the employee and that may reasonably raise an expectation of a conflict of interest.\nConflict of interest: a conflict of interest arises when an employee has private interests that could improperly influence, or be seen to influence, their decisions or the performance of their duties. Conflicts can be actual, potential or perceived and can be financial or non-financial in nature."]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["A1. Other significant sources of income:"], ["Do you have income from any sources other than your main source of employment income relating to:\ncontracts;\noffices held in return for payment or other reward; or\na trade, vocation or profession engaged in by you?", "YES☐ NO☐"], ["If yes, please provide details of this source of income."], ["Please explain how this income may reasonably raise an expectation of conflict of interest, or a material interference with your public duties. Alternatively, please explain why it does not."], ["A2. Office holder:"], ["Do you hold office in any public or private:\ncompany;\ntrustee company;\nincorporated association; or\nother entity?", "YES☐\nNO☐"], ["If yes, please provide the name of the organisation and the office you hold."], ["Please explain how this office may reasonably raise an expectation of conflict of interest, or a material interference with your public duties. Alternatively, please explain why it does not."]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["A3. Shareholdings and other business interests:"], ["Do you have any shareholdings, investments or other business?\nThis includes a company, partnership, association or other entity, as well as nominee shareholders on behalf of the agency in government companies.", "YES☐\nNO☐"], ["If yes, please provide details about the nature of the interest of all such holdings (not the amount)."], ["Please explain how this/these shareholdings or investments may reasonably raise an expectation of conflict of interest, or a material interference with your duties. Alternatively, please explain why it does not."], ["A4. Trusts"], ["Are you:\na beneficiary of any trust(If so, who is the trustee?);\nthe trustee of any trust; or\nthe director of a trustee company in which a member of your family (to your knowledge) is a beneficiary?", "YES☐\nNO☐"], ["If yes, please provide details about the operations of the trust/s."], ["Please explain how the operation of the trust/s may reasonably raise an expectation of conflict of interest, or a material interference with your duties. Alternatively, please explain why it does not."], ["A5. Family interests"], ["To your knowledge, do any of the following apply to your family that may reasonably raise an expectation of conflict of interest:\nentered into any contract, agreement or understanding that gives rise to an obligation or expectation of reward;\nhave any shareholdings, investments or other business (this includes a company, partnership, association or other entity, as well as nominee shareholders on behalf of the agency in government companies.)", "YES☐ NO☐"], ["If yes, please provide details, including the nature of the interest and how the interest may reasonably raise an expectation of conflict of interest."], ["A6. Other financial interests"], ["Do you or a member of your family (to your knowledge) have any other significant financial or other interests of which you are aware, which could reasonably raise an expectation of a conflict of interest or material interference with your duties? These include financial interests that:\nhave been held;\nare currently held; or\nwill accrue.", "YES☐ NO☐"], ["If yes, please provide details of the financial interest."], ["Please explain how this/these financial interests could reasonably raise an expectation of conflict of interest, or a material interference with your duties."], ["A7. Other interests"], ["To your knowledge, are there any other arrangements or circumstances not already covered to declare which could constitute a conflict of interest?", "YES☐ NO☐"], ["If yes, please provide details of these arrangements or circumstances."], ["Please explain how these arrangements or circumstances of which you are aware, could reasonably raise an expectation of conflict of interest, or a material interference with your duties."]] },
      { kind: "PARAGRAPH", text: "I declare that to the best of my knowledge, the information I have provided in Section A of this declaration is true and correct. I undertake to advise if an actual, potential or perceived conflict arises in the future. If there is any change to the interests set out in Section A, I undertake to advise the responsible or delegate of any alterations or additions to my declaration within five working days.", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Signature of Declarant: ________________", ""], ["Name (please print): ________________", ""], ["Date: ________________________", ""]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section B. Manager’s assessment and management plan for conflict of interest risk (Employee’s manager to complete this section only in situations of potential conflict)"], ["I have made the following assessment:\n(tick appropriate box)", "No conflict of interest risk identified\n☐ I have noted the information contained in the declaration, considered the duties of the employee and I am satisfied that the declaration does not identify any actual, potential or perceived conflicts of interest [Go to Section D].\nRisk of conflict of interest identified\n☐ I have noted the information contained in the declaration, considered the duties of the employee and I have concluded that there is a risk of a conflict of interest. [Go to question B1]."], ["B1. Type of conflict of interest identified"], ["The following conflict of interest risk was identified:\nUseful information: manager to state the specific personal interest identified (e.g. financial interest; conflict of duty etc.) and detail how this raises an actual, potential or perceived conflict of interest with the employee’s duties."], [""], ["B2. Management plan for employee’s conflict of interest"], ["The employee and I will take the following action to manage the conflict of interest:\nUseful information: this management plan will ensure conflict risks are managed and resolved in favour of the firm’s and client’s interest rather than that of the employee and will be based on the following mitigation strategies:\nRestrict: restrictions are placed on the employee’s involvement in the matter\nRecruit: a disinterested third party is used to oversee part or all of the process that deals with the matter\nRemove: the employee removes himself/herself, or is removed, from the matter\nRelinquish or Resign: the employee relinquishes the private interest that is creating the conflict. Where relinquishing the interest is not possible (e.g. relationship with family) and the conflict cannot be managed in the firm’s and client’s interest using one of the other options above, the employee may consider resigning."], [""], ["I will ensure this management plan is reviewed:", "☐ Within 1 month ☐ Within 3 months ☐ Within 6 months\n☐ Within 12 months ☐ N/A as the conflict is a one-off of short duration\n☐ Other (specify):"]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section C. Employee Declarations"], ["Employee declaration (only required where a conflict of interest risk is identified)"], ["The actions described in Section B2 of the form have been put in place to effectively manage any actual, perceived or potential conflict of interest disclosed in Sections A. I undertake to adhere to any conflict of interest risk management plan set out in Section B, which is in place to ensure that the Department’s reputation and the firm’s and client’s interest is adequately protected.\nI request approval to accept/continue the position noted above. I undertake that in the event of any change in my interest of appointment, I will immediately notify Compliance. I agree that I will resign from the external entity if the hours required become excessive or if a conflict of interest arises.\nIn the event that approval is given for my affiliation with an external entity which has a banking relationship with any part the Firm, I undertake that I will not be the Person handling the account and will not be involved in any business decisions."], ["Signature of Employee: _________________________\nName (please print): _________________________\nDate: ______/______/______"]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Section D. Manager Declaration"], ["Manager declaration (must be signed by manager – Strike out inapplicable)"], ["☐ No conflict and therefore no further action required\n☐ The actions described in Section B of the form have been put in place to effectively manage any actual, perceived or potential conflict of interest disclosed in Sections A. I undertake to adhere to any conflict of interest risk management plan set out in Section B, and to monitor my employee’s adherence to the management plan, which is in place to ensure that the Department’s reputation and the public interest is adequately protected."], ["Signature of Manager: _________________________\nName (please print): _________________________\nDate: ______/______/______"]] },
    ],
  },
  DFSA_CONDUCT_PRINCIPLES: {
    printed: {},
    blocks: [
      { kind: "HEADING", text: "DFSA Conduct Principles for Individuals", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "☒ I hereby undertake that I will comply with the rules and regulations stipulated by DFSA at all times", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "☒ I will follow the conduct principles for individuals stated in the DFSA rule book.", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Principle", "Summary"], ["Integrity", "Will observe high standards of integrity and fair dealing."], ["Due skill, care and diligence", "Will act with due skill, care and diligence in carrying out every Licensed Function"], ["Market conduct", "Will observe proper standards of conduct in financial markets in carrying out every Licensed Function."], ["Relations with the DFSA", "Will deal with the DFSA in an open and cooperative manner and will disclose appropriately any information of which the DFSA would reasonably be expected to be notified."], ["Management, systems and control", "Will take reasonable care to ensure that the business is organized so that it can be managed and controlled effectively."], ["Compliance", "Will take reasonable care to ensure that the firm complies with any legislation applicable in the DIFC."], ["Disclosure to DFSA", "Will disclose appropriately any information for which the DFSA would reasonably expect to be notified."]] },
      { kind: "PARAGRAPH", text: "☒ I acknowledge that breaching a conduct principle can make me subject to disciplinary action and may indicate that I am no longer fit and proper to perform a Function and the DFSA may consider suspending or withdrawing Individual status on that basis (as applicable).", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Declaration by the Employee:", strong: true, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I hereby declare that the details are set out hereunder, are complete and accurate and acknowledge that if there is any change in this declaration, I shall inform the Compliance Officer of such fact.", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Signature:"], ["Name: Bhanukumar Vittalam Lakshmana"], ["Position: Director"], ["Date: 18/02/2026"]] },
    ],
  },
  DATA_CONSENT: {
    printed: {"firmName": "Amaltas Partners Limited"},
    blocks: [
      { kind: "HEADING", text: "Employee’s Consent for Data Collection, Processing, Storage, Disclosure and Erasure", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I acknowledge that I have read the Employment Contract and hereby accept the policies and procedures contained therein. I understand that the Employee Handbook may be revised by the organization without prior notice and that such revisions may supersede, modify, or eliminate existing policies, procedures, and benefits. I acknowledge and agree that it is my responsibility to abide by the Employee Handbook at all times.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I confirm that my acceptance of the Employee Handbook/Offer Letter/Letter of Engagement conveyed here includes and implies consent to any revisions made to it and communicated to me without the requirement of the organization having to obtain specific consent from me again, unless I express a contrary intention in writing. I authorize {{firmName}} to collect, process, store, disclose and erase my Personal Information in accordance with the organization’s Policies, which I have read and understood. I confirm that I have been provided relevant training and guidance in this regard. I hereby convey my consent to the collection and processing of my Personal Information and confirm that this consent applies to all the Personal Information currently listed in the Privacy Policy of the organization without the need to obtain any further or specific consent from me.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I understand and confirm that this consent will be valid throughout the term of my employment/association with the organization. I further understand and agree that after cessation of my employment with the organization my Personal Information may be used for reference checks and enquiries, if any.", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "Declaration by the Employee:", strong: true, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I hereby declare that I have read the above declaration.", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Signature:"], ["Name: Bhanukumar Vittalam Lakshmana"], ["Position: Director"], ["Date: 18/02/2026"]] },
    ],
  },
  FIT_AND_PROPER: {
    printed: {"firmName": "AMALTAS PARTNERS LIMITED"},
    blocks: [
      { kind: "PARAGRAPH", text: "{{firmName}}", strong: false, number: null, rows: [] },
      { kind: "HEADING", text: "Fit and Proper Declaration", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "All staff and BOD Members should complete the following certification at the time of joining and every year thereafter:", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["S No", "Have you ever:", "YES", "NO"], ["1", "Been convicted or been found guilty by any court of competent jurisdiction of any offence other than a minor road traffic offence?", "☐ ", "☐ "], ["2", "Been the subject of disciplinary procedures by a government body or agency or any self-regulatory organisation or other professional body?", "☐ ", "☐ "], ["3", "Contravened any provision of financial services legislation or rules, regulations, statements, principles or codes of practice made under or by a financial services regulator or other supervisory body?", "☐ ", "☐ "], ["4", "Been refused or restricted the right to carry on a trade, business or profession requiring a license, registration or other authority?", "☐ ", "☐ "], ["5", "Been dismissed or requested to resign from any office of employment?", "☐ ", "☐ "], ["6", "Been concerned with the management of a company which has been or is currently the subject of an investigation into an allegation of misconduct or malpractice?", "☐ ", "☐ "], ["7", "Received an adverse finding in a civil action by any court of competent jurisdiction of fraud, misfeasance or other misconduct, whether in connection with the formation or management of a corporation or otherwise?", "☐ ", "☐ "], ["8", "Received an adverse finding in an agreed settlement in a civil action by any court or tribunal of competent jurisdiction which resulted in an award against an individual in excess of USD 10,000 or awards that total more than USD 10,000?", "☐ ", "☐ "], ["9", "Been the subject of an order of disqualification as a Director, or otherwise to act in the management or conduct of the affairs of a corporation by a court of competent jurisdiction or regulator?", "☐ ", "☐ "], ["10", "Been a director or partner of, or been concerned in the management of, a company or partnership which has gone into insolvent liquidation whilst the individual was connected with that company or partnership, or within one year of such a connection?", "☐ ", "☐ "], ["11", "Been the subject of a complaint in connection with a financial service or ancillary service which related to integrity, competence or financial soundness?", "☐ ", "☐ "], ["12", "Been censured, disciplined or publicly criticised by, or the subject of, a court order at the instigation of a financial services regulator or any officially appointed inquiry?", "☐ ", "☐ "], ["13", "Ever become bankrupt, applied to take the benefit of a law for the benefit of bankrupt or insolvent debtors, compounded with your creditors or assigned your remuneration the benefit of creditors?", "☐ ", "☐ "]] },
      { kind: "PARAGRAPH", text: "Declaration by the Firm’s Employee:", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "I hereby declare that the details are set out hereunder, are complete and accurate and acknowledge that if there is any change in this declaration, I shall inform the Compliance Officer of such fact.", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Individual’s Name", ""], ["Individual’s Signature", ""], ["Date", ""]] },
    ],
  },
  PERSONAL_ACCOUNT_DEALING: {
    printed: {},
    blocks: [
      { kind: "HEADING", text: "Personal Account Dealing Declaration", strong: false, number: null, rows: [] },
      { kind: "PARAGRAPH", text: "To be completed and submitted (to Compliance) by staff", strong: false, number: null, rows: [] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Name of Staff", ""], ["Title", ""], ["Period", "Jan 2024 to Dec 2024"]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["☐ New Joinee", "I am a new joinee and accept that the requirements set out in the manual form part of my employment contract\nI have read and understood the relevant rules and regulations of Personal Account Dealing.\nI understand that the Personal Account Dealing Policy is a condition of my contract of employment with the firm and any breach of these rules may constitute grounds for disciplinary action up to and including dismissal.\nI confirm that I will adhere to the letter and spirit of Personal Account Dealing Policy and that I will seek approval for and notify Compliance of ALL personal account dealing transactions that I intend to undertake."], ["☐ Annual Declaration", "☐ I confirm that I have requested approval for and notified Compliance of ALL personal account transactions that I have undertaken and completed for each transaction. All such transactions are listed below.\nOR\n☐ I confirm that I have not undertaken any personal account transactions, as defined in the Personal Account Dealing Policy.\nDeclarations:\nI affirm that the information disclosed is complete, accurate and to the best of my knowledge not misleading. I accept responsibility for complying with Policy and assume responsibility for updating this disclosure as necessary.\nI have read and understood the relevant rules and regulations of Personal Account Dealing.\nI understand that the Personal Account Dealing Policy is a condition of my contract of employment with the firm and any breach of these rules may constitute grounds for disciplinary action up to and including dismissal.\nI confirm that I have not communicated any information or opinion to another person in circumstances where I knew, or ought to have known, that the person would as a result, enter into such a transaction or procure some other person to do so\nI hereby authorize to receive duplicate copies of all transaction confirmation statements and all account statements with respect to any securities account I maintain with any broker, dealer, investment manager or bank.\nI further acknowledge that any communications concerning pre-clearances of Restricted investment transactions required pursuant to the policy may be recorded by the Firm.\nI confirm that I will adhere to the letter and spirit of Personal Account Dealing Policy and that I will seek approval for and notify Compliance of ALL personal account dealing transactions that I intend to undertake.\nList of transactions undertaken are as below:\nSno — Date — Name of Staff — Name of related party — Stockbroking account name — Account number — Investment product details\n(Stock / other securities) — Quantity — Remarks\n\n"]] },
      { kind: "TABLE", text: "", strong: false, number: null, rows: [["Name:", "Individual’s signature:"], ["Date:", ""]] },
    ],
  },
};
